### ISSUE TITLE
Example of 'resign' please!

### ISSUE THREAD

**Issue by hokster7** [fastlane/examples#2]
I would like to see one.

I've got a target with three configurations corresponding to DEVELOPMENT, STAGING and PRODUCTION environments. I've configured three corresponding schemes in Xcode so that I can switch between them.

I actually want to configure Xcode so that the **STAGING and PRODUCTION** configurations both use the `iOS Developer` code signing identity. This is so that I can use Xcode to `Run` the schemes on the local developer machine.

My use case is I want to testing for the correct [bundling of Javascript resources for React Native](http://herman.asia/building-a-flashcard-app-with-react-native) in the same configuration, for instance.

`resign` comes into play because I want to distribute these builds to TestFlight, and that demands that the code signing identity is `iOS Distribution`. So if I'm able to build the IPA as normal, and then use `resign` to supplant in the distribution code signing and provisioning profiles then bob's your uncle :)

**Comment by KrauseFx** [comment]
@fatuhoku You can pass the code signing identity using environment variables as described in the [Code Signing Guide](https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md) :+1:

**Comment by hokster7** [comment]
@KrauseFx Okay thanks!  The resign part of it seems to work okay, except on `deliver` I run into KrauseFx/fastlane#477. :/  Closing this one.
