### ISSUE TITLE
The Fastlane Fastfile link is broken

### ISSUE THREAD

**Issue by jstheoriginal** [fastlane/examples#20]
https://github.com/KrauseFx/fastlane/blob/master/fastlane/Fastfile

:)

**Comment by KrauseFx** [comment]
Thanks for letting us know @jstheoriginal :+1:

**Comment by jstheoriginal** [comment]
😎

On Thu, Mar 17, 2016 at 11:57 AM Felix Krause

<
mailto:Felix Krause notifications@github.com

> wrote:

Thanks for letting us know
https://github.com/jstheoriginal
