### ISSUE TITLE
Create Crashlytics beta sharing link

### ISSUE THREAD

**Issue by Vishal-Singh-Panwar** [fastlane/examples#29]
Is there a way to create share link of ipa in Crashlytic Beta after upload? Like we get `HOCKEY_DOWNLOAD_LINK` as output variable for Hockey App.

**Comment by KrauseFx** [comment]
That's a great idea, currently it's not possible. Could you submit an issue on the fastlane main repo for this? 👍

**Comment by Vishal-Singh-Panwar** [comment]
Submitted the [issue](https://github.com/fastlane/fastlane/issues/5222). 👍

**Comment by KrauseFx** [comment]
Perfect, thanks
