### ISSUE TITLE
How do we use fastlane with fabric without a developers account?

### ISSUE THREAD

**Issue by rlam3** [fastlane/examples#39]
How do we use fastlane with fabric without a developers account? Would love to see a tutorial / documentation on this. Maybe even a video perhaps would work. Thankss!

**Comment by KrauseFx** [comment]
You need a developer account to sign your application for distribution, that's a requirement by Apple.

**Comment by rlam3** [comment]
@KrauseFx Thanks for your response. When you say is requirement by apple. Does this mean it is the paid account or can it also be with the unpaid account too? Just wanted a bit more clarification. Thanks.

Also do you recommend using fastlane / distribute beta via fabric? or would you it be better to use fastlane standalone to deploy ? Thanks!

**Comment by KrauseFx** [comment]
For beta distribution via Ad Hoc you need a paid developer account membership 👍

**Comment by KrauseFx** [comment]
For further questions please submit an issue on the [main GitHub page](https://github.com/fastlane/fastlane)
