### ISSUE TITLE
Include recommended gitignore

### ISSUE THREAD

**Issue by fulldecent** [fastlane/examples#5]
(Because `fastlane-example` is deprecated, I have updated this issue.)

I am requesting a recommended gitignore to use with fastlane. I have just gotten fastlane set up in my project and am ready to `git commit`. There is a lot of ugliness in `git status` including:

```
/fastlane/report.xml -- temporary fastlane profiling data
/fastlane/Error*.png -- temporary `deliver` error output
/fastlane/Preview.html -- temporary `deliver` preview output
/fastlane/screenshots/*/*-portrait.png -- generated screenshots
/fastlane/screenshots/*/*-landscape.png -- generated screenshots
/fastlane/screenshots/*/*-portrait_framed.png -- generated screenshots, framed
/fastlane/screenshots/*/*-landscape_framed.png -- generated screenshots, framed
/fastlane/screenshots/screenshots.html -- generated screenshot index
```

I am adding these all to my `.gitignore`, but it would be preferred if fastlane would have a baseline gitignore posted here or on https://github.com/KrauseFx/fastlane

Because users will need to paste this into `.gitignore` themselves, it would be reasonable that they will understand what is going on, and update the file, if they start changing default values which cause these above items to be inaccurate.

**Comment by KrauseFx** [comment]
I like the idea, where should this be posted? Maybe in the [Advanced.md](https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md)?

**Comment by fulldecent** [comment]
Sounds good, PR created -- https://github.com/KrauseFx/fastlane/pull/535
